#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

DATADIR="$DIRNAME"
CONFDIR="$DIRNAME"

if [ "$JAVA" = "" ]; then
  JAVA=`which java`
  if [ "$JAVA" = "" ]; then
    if [ "$JAVA_HOME" = "" ]; then
      echo 'Unable to start a JVM : $JAVA is not set and java is not in PATH and $JAVA_HOME is not set'
      exit
    fi
    JAVA="$JAVA_HOME/bin/java"
  fi
fi

if [ "$JAVA_OPTS" = "" ]; then
  JAVA_OPTS=-Djava.net.useSystemProxies=true
fi

if [ "$VESTIGE_BASE" = "" ]; then
  VESTIGE_BASE="$DIRNAME/base"
fi

if [ ! -d "$VESTIGE_BASE" ]; then
  mkdir -p "$VESTIGE_BASE"
  cp -R "$CONFDIR/template/." "$VESTIGE_BASE"
fi

if [ "$VESTIGE_DATA" = "" ]; then
  VESTIGE_DATA="$DIRNAME/data"
fi

if [ "$VESTIGE_SECURITY" = "" ]; then
  VESTIGE_SECURITY=true
fi

if [ "$VESTIGE_LISTENER_PORT" = "" ]; then
  VESTIGE_LISTENER_PORT=0
fi

if [ ${#VESTIGE_OPTS[@]} -eq 0 ]; then
  VESTIGE_OPTS=($JAVA_OPTS)
fi
if [ ${#VESTIGE_DEBUG} -ne 0 ]; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000)
fi

MAVEN_LAUNCHER_FILE="$DATADIR/m2/vestige-se.xml"

MAVEN_SETTINGS_FILE="$VESTIGE_BASE/m2/settings.xml"

MAVEN_RESOLVER_CACHE_FILE="$VESTIGE_DATA/m2/resolver-cache.ser"

LOGBACK_CONFIGURATION_FILE="$VESTIGE_BASE/logback.xml"

if [ ! -f "$LOGBACK_CONFIGURATION_FILE" ]; then
  cp "$CONFDIR/template/logback.xml" "$LOGBACK_CONFIGURATION_FILE"
fi

VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dvestige.mavenRepository="$DATADIR/repository" -Djava.util.logging.manager=fr.gaellalire.vestige.core.logger.JULLogManager -Dlogback.logsDirectory="$VESTIGE_BASE/logs" -Dlogback.configurationFile="$LOGBACK_CONFIGURATION_FILE")

if "$JAVA" --add-modules java.xml.bind -version >/dev/null 2>&1; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" --add-modules java.xml.bind --add-opens=java.logging/java.util.logging=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/sun.security.jca=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.sql/java.sql=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED)
fi

exec "$JAVA" "${VESTIGE_OPTS[@]}" -jar "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" frcp "$DATADIR" "$DATADIR/unix-classpath.txt" fr.gaellalire.vestige.jvm_enhancer.boot.JVMEnhancer "$DATADIR" "$DATADIR/jvm_enhancer.properties" fr.gaellalire.vestige.resolver.maven.VestigeMavenResolver "$MAVEN_LAUNCHER_FILE" "$MAVEN_SETTINGS_FILE" "$MAVEN_RESOLVER_CACHE_FILE" "$VESTIGE_BASE" "$VESTIGE_DATA" "$VESTIGE_SECURITY" "$VESTIGE_LISTENER_PORT"
