#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

VESTIGE_SYSTEM_DATA="$DIRNAME"
VESTIGE_SYSTEM_CONFIG="$DIRNAME"

if [ "$VESTIGE_JAVA" = "" ]; then
  if [ "$JAVA" = "" ]; then
    VESTIGE_JAVA=`which java`
    if [ "$VESTIGE_JAVA" = "" ]; then
      if [ "$JAVA_HOME" = "" ]; then
        echo 'Unable to start a JVM : $VESTIGE_JAVA and $JAVA are not set and java is not in PATH and $JAVA_HOME is not set'
        exit
      fi
      VESTIGE_JAVA="$JAVA_HOME/bin/java"
    fi
  else
    VESTIGE_JAVA="$JAVA"
  fi
fi

if [ "$JAVA_OPTS" = "" ]; then
  JAVA_OPTS=-Djava.net.useSystemProxies=true
fi

if [ "$VESTIGE_CONFIG" = "" ]; then
  VESTIGE_CONFIG="$DIRNAME/config"
fi

if [ ! -d "$VESTIGE_CONFIG" ]; then
  mkdir -p "$VESTIGE_CONFIG"
  if [ -d "$VESTIGE_SYSTEM_CONFIG/template" ]; then
    cp -R "$VESTIGE_SYSTEM_CONFIG/template/." "$VESTIGE_CONFIG"
  fi
fi

if [ "$VESTIGE_DATA" = "" ]; then
  VESTIGE_DATA="$DIRNAME/data"
fi

if [ "$VESTIGE_CACHE" = "" ]; then
  VESTIGE_CACHE="$DIRNAME/cache"
fi

if [ "$VESTIGE_SECURITY" = "" ]; then
  VESTIGE_SECURITY=true
fi

if [ "$VESTIGE_LISTENER_PORT" = "" ]; then
  VESTIGE_LISTENER_PORT=0
fi

# VESTIGE_OPTS=("-Doption=value" "-Xmx1024m")
# export DECLARE_VESTIGE_OPTS=$(declare -p VESTIGE_OPTS)
DECLARE_VESTIGE_OPTS=$(echo "$DECLARE_VESTIGE_OPTS" | grep "^\(declare\|typeset\) -a VESTIGE_OPTS=")
if [ "${#DECLARE_VESTIGE_OPTS}" -ne 0 ]; then
  eval "$DECLARE_VESTIGE_OPTS" >/dev/null 2>&1 || VESTIGE_OPTS=($JAVA_OPTS)
else
  VESTIGE_OPTS=($JAVA_OPTS)
fi

if [ ${#VESTIGE_DEBUG} -ne 0 ]; then
  if [ "$VESTIGE_DEBUG_SUSPEND" = "" ]; then
    VESTIGE_DEBUG_SUSPEND="n"
  fi
  if [ "$VESTIGE_DEBUG_HOST" = "" ]; then
    VESTIGE_DEBUG_HOST="127.0.0.1"
  fi
  if [ "$VESTIGE_DEBUG_PORT" = "" ]; then
    VESTIGE_DEBUG_PORT="8000"
  fi
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -agentlib:jdwp=transport=dt_socket,server=y,suspend=${VESTIGE_DEBUG_SUSPEND},address=${VESTIGE_DEBUG_HOST}:${VESTIGE_DEBUG_PORT})
fi

if [ ${#VESTIGE_CONSOLE_ENCODING} -ne 0 ]; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dconsole.encoding=$VESTIGE_CONSOLE_ENCODING -Dsun.stdout.encoding=$VESTIGE_CONSOLE_ENCODING -Dsun.stderr.encoding=$VESTIGE_CONSOLE_ENCODING)
fi

MAVEN_SETTINGS_FILE="$VESTIGE_CONFIG/m2/settings.xml"

LOGBACK_LOGS_DIRECTORY="$VESTIGE_CACHE/logs"

mkdir -p "$LOGBACK_LOGS_DIRECTORY"

LOGBACK_CONFIGURATION_FILE="$VESTIGE_CONFIG/logback.xml"

if [ ! -f "$LOGBACK_CONFIGURATION_FILE" ]; then
  LOGBACK_CONFIGURATION_FILE="$VESTIGE_SYSTEM_CONFIG/logback.xml"
fi

MAVEN_CACERTS="$VESTIGE_CONFIG/cacerts.p12"

if [ ! -f "$MAVEN_CACERTS" ]; then
  MAVEN_CACERTS="$VESTIGE_SYSTEM_CONFIG/cacerts.p12"
fi

VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dvestige.mavenRepository="$VESTIGE_SYSTEM_DATA/repository" -Djava.util.logging.manager=fr.gaellalire.vestige.core.logger.JULLogManager)

VESTIGE_CORE_FILE_ENCODING=UTF-8

VESTIGE_CORE_RELATIVE_DIRECTORY="$VESTIGE_SYSTEM_DATA"

if "$VESTIGE_JAVA" --add-modules java.base -version >/dev/null 2>&1; then
  export VESTIGE_CORE_MODULEPATH_FILE="$VESTIGE_SYSTEM_DATA/unix-classpath.txt"
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" --add-modules ALL-DEFAULT --patch-module "java.base=$VESTIGE_SYSTEM_DATA/lib/moduleEncapsulationBreaker.jar")
  VESTIGE_ARGS=(-p "$VESTIGE_SYSTEM_DATA/lib/vestige.core-${vestige.core.version}.jar" -m fr.gaellalire.vestige.core --env-to-prop LOGBACK_LOGS_DIRECTORY logback.logsDirectory --env-to-prop LOGBACK_CONFIGURATION_FILE logback.configurationFile --add-modules fr.gaellalire.vestige.jvm_enhancer.boot,fr.gaellalire.vestige.edition.maven_main_launcher emp fr.gaellalire.vestige.logback_enhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" fr.gaellalire.vestige.jvm_enhancer.boot)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$VESTIGE_SYSTEM_DATA" "$VESTIGE_SYSTEM_DATA/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher)
  MAVEN_LAUNCHER_FILE="$VESTIGE_SYSTEM_DATA/m2/vestige-se.xml"
  MAVEN_RESOLVER_CACHE_FILE="$VESTIGE_CACHE/m2/resolver-cache.ser"
else
  export VESTIGE_CORE_CLASSPATH_FILE="$VESTIGE_SYSTEM_DATA/unix-classpath-6to8.txt"
  VESTIGE_ARGS=(-jar "$VESTIGE_SYSTEM_DATA/lib/vestige.core-${vestige.core.version}.jar" --env-to-prop LOGBACK_LOGS_DIRECTORY logback.logsDirectory --env-to-prop LOGBACK_CONFIGURATION_FILE logback.configurationFile --before 'javax/xml/bind/.*' ecp fr.gaellalire.vestige.logback_enhancer.LogbackEnhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" fr.gaellalire.vestige.jvm_enhancer.boot.JVMEnhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$VESTIGE_SYSTEM_DATA" "$VESTIGE_SYSTEM_DATA/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher.MavenMainLauncher)
  MAVEN_LAUNCHER_FILE="$VESTIGE_SYSTEM_DATA/m2/vestige-se-6to8.xml"
  MAVEN_RESOLVER_CACHE_FILE="$VESTIGE_CACHE/m2/resolver-cache-6to8.ser"
fi

if [ "$HOSTNAME" != "" ]; then
  export HOSTNAME
fi
export VESTIGE_CORE_FILE_ENCODING VESTIGE_CORE_RELATIVE_DIRECTORY LOGBACK_LOGS_DIRECTORY LOGBACK_CONFIGURATION_FILE MAVEN_LAUNCHER_FILE MAVEN_SETTINGS_FILE MAVEN_CACERTS MAVEN_RESOLVER_CACHE_FILE VESTIGE_SYSTEM_CONFIG VESTIGE_CONFIG VESTIGE_DATA VESTIGE_CACHE VESTIGE_SECURITY VESTIGE_LISTENER_PORT

exec "$VESTIGE_JAVA" "${VESTIGE_OPTS[@]}" "${VESTIGE_ARGS[@]}"
