#!/bin/bash

DIRNAME=`dirname "$0"`
if [ "$DIRNAME" = "." ]; then
  DIRNAME="$PWD"
fi

DATADIR="$DIRNAME"
CONFDIR="$DIRNAME"

if [ "$JAVA" = "" ]; then
  JAVA=`which java`
  if [ "$JAVA" = "" ]; then
    if [ "$JAVA_HOME" = "" ]; then
      echo 'Unable to start a JVM : $JAVA is not set and java is not in PATH and $JAVA_HOME is not set'
      exit
    fi
    JAVA="$JAVA_HOME/bin/java"
  fi
fi

if [ "$JAVA_OPTS" = "" ]; then
  JAVA_OPTS=-Djava.net.useSystemProxies=true
fi

if [ "$VESTIGE_BASE" = "" ]; then
  VESTIGE_BASE="$DIRNAME/base"
fi

if [ ! -d "$VESTIGE_BASE" ]; then
  mkdir -p "$VESTIGE_BASE"
  cp -R "$CONFDIR/template/." "$VESTIGE_BASE"
fi

if [ "$VESTIGE_DATA" = "" ]; then
  VESTIGE_DATA="$DIRNAME/data"
fi

if [ "$VESTIGE_SECURITY" = "" ]; then
  VESTIGE_SECURITY=true
fi

if [ "$VESTIGE_LISTENER_PORT" = "" ]; then
  VESTIGE_LISTENER_PORT=0
fi

if [ ${#VESTIGE_OPTS[@]} -eq 0 ]; then
  VESTIGE_OPTS=($JAVA_OPTS)
fi
if [ ${#VESTIGE_DEBUG} -ne 0 ]; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000)
fi

VESTIGE_CONSOLE_ENCODING_OPTION=""

if [ ${#VESTIGE_CONSOLE_ENCODING} -ne 0 ]; then
  VESTIGE_CONSOLE_ENCODING_OPTION="--console-encoding $VESTIGE_CONSOLE_ENCODING"
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dlogback.consoleCharset=$VESTIGE_CONSOLE_ENCODING)
fi

MAVEN_LAUNCHER_FILE="$DATADIR/m2/vestige-se.xml"

MAVEN_SETTINGS_FILE="$VESTIGE_BASE/m2/settings.xml"

MAVEN_RESOLVER_CACHE_FILE="$VESTIGE_DATA/m2/resolver-cache.ser"

LOGBACK_CONFIGURATION_FILE="$VESTIGE_BASE/logback.xml"

if [ ! -f "$LOGBACK_CONFIGURATION_FILE" ]; then
  cp "$CONFDIR/template/logback.xml" "$LOGBACK_CONFIGURATION_FILE"
fi

VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" -Dvestige.mavenRepository="$DATADIR/repository" -Djava.util.logging.manager=fr.gaellalire.vestige.core.logger.JULLogManager -Dlogback.logsDirectory="$VESTIGE_BASE/logs" -Dlogback.configurationFile="$LOGBACK_CONFIGURATION_FILE" -Djavax.net.ssl.trustStore="$VESTIGE_BASE/cacert.jks")

if "$JAVA" --add-modules java.base -version >/dev/null 2>&1; then
  VESTIGE_OPTS=("${VESTIGE_OPTS[@]}" --add-modules ALL-DEFAULT --patch-module "java.base=$DATADIR/lib/moduleEncapsulationBreaker.jar")
  VESTIGE_ARGS=(-p "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" -m fr.gaellalire.vestige.core $VESTIGE_CONSOLE_ENCODING_OPTION --add-modules fr.gaellalire.vestige.edition.maven_main_launcher fremp "$DATADIR" "$DATADIR/unix-classpath.txt" UTF-8 fr.gaellalire.vestige.jvm_enhancer.boot)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$DATADIR" "$DATADIR/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher)
else
  VESTIGE_ARGS=(-jar "$DATADIR/lib/vestige.core-${vestige.core.version}.jar" $VESTIGE_CONSOLE_ENCODING_OPTION --before 'javax/xml/bind/.*' frecp "$DATADIR" "$DATADIR/unix-classpath.txt" UTF-8 fr.gaellalire.vestige.jvm_enhancer.boot.JVMEnhancer)
  VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$DATADIR" "$DATADIR/jvm_enhancer.properties" fr.gaellalire.vestige.edition.maven_main_launcher.MavenMainLauncher)
fi

VESTIGE_ARGS=("${VESTIGE_ARGS[@]}" "$MAVEN_LAUNCHER_FILE" "$MAVEN_SETTINGS_FILE" "$MAVEN_RESOLVER_CACHE_FILE" "$VESTIGE_BASE" "$VESTIGE_DATA" "$VESTIGE_SECURITY" "$VESTIGE_LISTENER_PORT")

exec "$JAVA" "${VESTIGE_OPTS[@]}" "${VESTIGE_ARGS[@]}"
