FROM archlinux

RUN pacman -Syu --noconfirm openssh sudo fakeroot binutils

RUN useradd builder -u 1000 -m -G users,wheel && \
    echo "builder ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    chown -R builder /home/builder && \
    /usr/bin/ssh-keygen -A

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
