/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_gaellalire_vestige_jvm_enhancer_windows_WindowsShutdownHook */

#ifndef _Included_fr_gaellalire_vestige_jvm_enhancer_runtime_windows_WindowsShutdownHook
#define _Included_fr_gaellalire_vestige_jvm_enhancer_runtime_windows_WindowsShutdownHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_gaellalire_vestige_jvm_enhancer_windows_WindowsShutdownHook
 * Method:    nativeRegister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_fr_gaellalire_vestige_jvm_1enhancer_runtime_windows_WindowsShutdownHook_nativeRegister
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
