#!/bin/bash

VESTIGE_VERSION=`cat ../standard_edition_standalone/pom.xml | grep -m 1 version | sed 's/.*>\(.*\)<\/version>/\1/g'`

rm -r target
mkdir target
hdiutil convert -format UDRW -ov -o target/wc.dmg src/wc.dmg
hdiutil resize -size 100M target/wc.dmg
HDIDEV=$(hdiutil attach target/wc.dmg -noautoopen -nobrowse -mountpoint target/wc | grep "Apple_HFS" | cut -d$'\t' -f 1)
rm -rf src/Vestige.app/Contents/Resources/vestige_home/
cp -r src/Vestige.app target/wc/
unzip -d target/wc/Vestige.app/Contents/Resources/vestige_home ../standard_edition_standalone/target/vestige.assemblies.standard_edition_standalone-$VESTIGE_VERSION-unix.zip
sed -i~ -e 's/-Djava.util.logging.manager/-Dapple.awt.UIElement=true -Djava.util.logging.manager/' -e 's/VESTIGE_CONFIG=.*/VESTIGE_CONFIG="$HOME\/Library\/Preferences\/Vestige"/' -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="$HOME\/Library\/Application Support\/Vestige"/' -e 's/VESTIGE_CACHE=.*/VESTIGE_CACHE="$HOME\/Library\/Caches\/Vestige"/' -e 's/$VESTIGE_CACHE\/logs/$HOME\/Library\/Logs\/Vestige/' target/wc/Vestige.app/Contents/Resources/vestige_home/vestige
rm target/wc/Vestige.app/Contents/Resources/vestige_home/vestige~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="$HOME\/Library\/Application Support\/Vestige"/' target/wc/Vestige.app/Contents/Resources/vestige_home/vestigessh
rm target/wc/Vestige.app/Contents/Resources/vestige_home/vestigessh~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="$HOME\/Library\/Application Support\/Vestige"/' target/wc/Vestige.app/Contents/Resources/vestige_home/vestigeweb
rm target/wc/Vestige.app/Contents/Resources/vestige_home/vestigeweb~
rm target/wc/Vestige.app/Contents/Resources/vestige_home/lib/*.so
find target -name .svn -exec rm -rf {} \;
# SetFile -c icnC target/wc/.VolumeIcon.icns
GetFileInfo target/wc/.VolumeIcon.icns
SetFile -a C target/wc
rm -rf target/wc/.fseventsd
hdiutil detach $HDIDEV
hdiutil convert target/wc.dmg -format UDZO -imagekey zlib-level=9 -o target/vestige-$VESTIGE_VERSION.dmg
SetFile -a C target/vestige-$VESTIGE_VERSION.dmg
