#!/bin/bash

VESTIGE_VERSION=`cat ../standard_edition_standalone/pom.xml | grep -m 1 version | sed 's/.*>\(.*\)<\/version>/\1/g'`
VESTIGE_ARCH_VERSION=`echo $VESTIGE_VERSION | sed 's/-SNAPSHOT//g'`

rm -r target
mkdir -p target/vestige_arch/etc/vestige
unzip -d target/vestige ../standard_edition_standalone/target/vestige.assemblies.standard_edition_standalone-$VESTIGE_VERSION-unix.zip
sed -i~ -e 's/VESTIGE_CONFIG=.*/VESTIGE_CONFIG="${XDG_CONFIG_HOME:-$HOME\/.config}\/vestige"/' -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' -e 's/VESTIGE_CACHE=.*/VESTIGE_CACHE="${XDG_CACHE_HOME:-$HOME\/.cache}\/vestige"/' -e 's/DATADIR=.*/DATADIR=\/usr\/share\/vestige/' -e 's/CONFDIR=.*/CONFDIR=\/etc\/vestige\//' target/vestige/vestige
rm target/vestige/vestige~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' target/vestige/vestigessh
rm target/vestige/vestigessh~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' target/vestige/vestigeweb
rm target/vestige/vestigeweb~
mkdir -p target/vestige_arch/usr/share/vestige
mv target/vestige/repository target/vestige_arch/usr/share/vestige/repository
mv target/vestige/lib target/vestige_arch/usr/share/vestige/lib
mv target/vestige/m2 target/vestige_arch/usr/share/vestige/m2
mv target/vestige/unix-classpath.txt target/vestige_arch/usr/share/vestige/
mv target/vestige/vestige target/vestige_arch/usr/share/vestige/
mv target/vestige/vestigessh target/vestige_arch/usr/share/vestige/
mv target/vestige/vestigeweb target/vestige_arch/usr/share/vestige/
chmod +x target/vestige_arch/usr/share/vestige/vestige
mv target/vestige/jvm_enhancer.properties target/vestige_arch/usr/share/vestige/
rm target/vestige/README
mv target/vestige/* target/vestige_arch/etc/vestige/
sed -e 's/pkgver=.*/pkgver='$VESTIGE_ARCH_VERSION'/' src/PKGBUILD > target/PKGBUILD
find target \( -name .svn -o -name .DS_Store \) -exec rm -rf {} \;
ssh archbuilder rm -rf '~/target'
scp -r target archbuilder:.
ssh archbuilder 'cd target && makepkg -s --sign'
scp archbuilder:target/vestige-${VESTIGE_ARCH_VERSION}-1-any.pkg.tar.xz* target/ 
