#!/bin/bash

VESTIGE_VERSION=`cat ../standard_edition_standalone/pom.xml | grep -m 1 version | sed 's/.*>\(.*\)<\/version>/\1/g'`
VESTIGE_RPM_VERSION=`echo $VESTIGE_VERSION | sed 's/-SNAPSHOT//g'`

echo "$VESTIGE_VERSION $VESTIGE_RPM_VERSION"
rm -r target
mkdir target
unzip -d target/vestige-$VESTIGE_RPM_VERSION ../standard_edition_standalone/target/vestige.assemblies.standard_edition_standalone-$VESTIGE_VERSION-unix.zip
sed -i~ -e 's/VESTIGE_CONFIG=.*/VESTIGE_CONFIG="${XDG_CONFIG_HOME:-$HOME\/.config}\/vestige"/' -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' -e 's/VESTIGE_CACHE=.*/VESTIGE_CACHE="${XDG_CACHE_HOME:-$HOME\/.cache}\/vestige"/' -e 's/VESTIGE_SYSTEM_DATA=.*/VESTIGE_SYSTEM_DATA=\/usr\/share\/vestige/' -e 's/VESTIGE_SYSTEM_CONFIG=.*/VESTIGE_SYSTEM_CONFIG=\/etc\/vestige\//' target/vestige-$VESTIGE_RPM_VERSION/vestige
rm target/vestige-$VESTIGE_RPM_VERSION/vestige~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' target/vestige-$VESTIGE_RPM_VERSION/vestigessh
rm target/vestige-$VESTIGE_RPM_VERSION/vestigessh~
sed -i~ -e 's/VESTIGE_DATA=.*/VESTIGE_DATA="${XDG_DATA_HOME:-$HOME\/.local\/share}\/vestige"/' target/vestige-$VESTIGE_RPM_VERSION/vestigeweb
rm target/vestige-$VESTIGE_RPM_VERSION/vestigeweb~
sed -e 's/Version:        .*/Version:        '$VESTIGE_RPM_VERSION'/' -e 's/standard_edition_bootstrap.*-jar-with-dependencies.jar/standard_edition_bootstrap-'$VESTIGE_VERSION'-jar-with-dependencies.jar/' src/vestige.spec > target/vestige.spec
cp src/Makefile target/vestige-$VESTIGE_RPM_VERSION/
find target \( -name .svn -o -name .DS_Store \) -exec rm -rf {} \;
pushd target && tar -czf vestige.tar.gz vestige-$VESTIGE_RPM_VERSION && popd
scp target/vestige.tar.gz rpmbuilder:rpmbuild/SOURCES/vestige.tar.gz
scp target/vestige.spec rpmbuilder:rpmbuild/SPECS/vestige.spec
ssh rpmbuilder 'rpmbuild -bb ~/rpmbuild/SPECS/vestige.spec'
ssh rpmbuilder 'echo "" | setsid rpm --define "_gpg_name '$GPG_NAME'" --addsign rpmbuild/RPMS/noarch/vestige-'$VESTIGE_RPM_VERSION'-1.noarch.rpm'
scp rpmbuilder:rpmbuild/RPMS/noarch/vestige-$VESTIGE_RPM_VERSION-1.noarch.rpm target/vestige-$VESTIGE_RPM_VERSION-1.noarch.rpm
